Repository ColeHend/serving-solid-characters, pull requests merged in 2024-09, with the labels that each got.

#59 Coleh/class homebrew finish
  client/dev-dist/sw.js
  client/src/App.tsx
  client/src/components/homebrew/create/parts/classes/classes.tsx
  client/src/components/homebrew/create/parts/classes/sections/proficiency.tsx
  client/src/components/homebrew/create/parts/classes/sections/startEquipment.tsx
  client/src/shared/components/Chip/Chip.tsx
  client/src/shared/components/Chipbar/chipbar.tsx
  client/src/shared/components/Input/Input.tsx
  client/src/shared/components/Table/innerTable.tsx
  client/src/shared/components/Table/table.tsx
  client/src/shared/components/Tabs/tab.tsx
  client/src/shared/components/Tabs/tabs.tsx
  client/src/shared/customHooks/utility/Tools.ts
  client/src/shared/index.ts
Labels: bug, enhancement

#62 Slade infotab css
  client/src/components/infoTab/Spells/Spells.tsx
Labels: enhancement

#68 fixed data
  Controllers/DnDInfoController.cs
  Repositories/DndInfoRepository.cs
  Repositories/homeClass/Forgemaster.cs
  client/dev-dist/sw.js
  client/src/components/homebrew/create/parts/backgrounds/backgrounds.tsx
  client/src/components/homebrew/create/parts/classes/classes.tsx
  client/src/components/homebrew/create/parts/classes/levelBuilder.tsx
  client/src/components/homebrew/create/parts/classes/sections/featureModal.tsx
  client/src/components/homebrew/create/parts/classes/sections/startEquipment.tsx
  client/src/components/homebrew/create/parts/feats/feats.tsx
  client/src/components/homebrew/create/parts/subclasses/subclasses.tsx
  client/src/components/infoTab/Backgrounds/backgrounds.tsx
  client/src/components/infoTab/Feats/feats.tsx
  client/src/models/character.model.ts
  client/src/models/class.model.ts
  client/src/models/core.model.ts
  client/src/models/items.model.ts
  client/src/shared/components/modals/classModal/classModal.component.tsx
  client/src/shared/customHooks/dndInfo/srdinfo/fixClasses.ts
  client/src/shared/customHooks/dndInfo/srdinfo/useDnDClasses.ts
  client/src/shared/customHooks/dndInfo/useCharacters.ts
  client/src/shared/customHooks/useGetFeatures.ts
  client/src/shared/customHooks/utility/Tools.ts
  data/srd/classes.json
  extensions/classMappers.cs
  models/classJsonModel.cs
  models/entities/ClassEntity.cs
  tools/DbJsonTool.cs
  tools/NewClass.cs
  tools/ObjectTools.cs
Labels: bug, enhancement, MVP

#70 Slade infotab refactor
  client/src/components/homebrew/create/parts/spells/spells.tsx
  client/src/components/infoTab/Backgrounds/backgrounds.module.scss
  client/src/components/infoTab/Backgrounds/backgrounds.tsx
  client/src/components/infoTab/Backgrounds/searchBar/searchBar.tsx
  client/src/components/infoTab/Feats/feats.module.scss
  client/src/components/infoTab/Feats/feats.tsx
  client/src/components/infoTab/Feats/searchBar/searchBar.module.scss
  client/src/components/infoTab/Feats/searchBar/searchBar.tsx
  client/src/components/infoTab/Races/races.module.scss
  client/src/components/infoTab/Races/races.tsx
  client/src/components/infoTab/Races/sidebar.tsx
  client/src/components/infoTab/Races/subraces/subrace.module.scss
  client/src/components/infoTab/Races/subraces/subrace.tsx
  client/src/components/infoTab/Races/thePage.tsx
  client/src/components/infoTab/Spells/Spells.module.scss
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/components/infoTab/items/item.module.scss
  client/src/components/infoTab/items/item.tsx
  client/src/components/infoTab/items/parts/AdventuringEquip/AdventuringEquip.tsx
  client/src/components/infoTab/items/parts/Armors/Armors.module.scss
  client/src/components/infoTab/items/parts/Armors/Armors.tsx
  client/src/components/infoTab/items/parts/Weapons/Weapons.tsx
  client/src/components/infoTab/items/parts/Weapons/weapons.module.scss
  client/src/components/infoTab/viewClasses/viewClasses.module.scss
  client/src/components/infoTab/viewClasses/viewClasses.tsx
  client/src/index.tsx
  client/src/shared/components/Carosel/Carosel.tsx
  client/src/shared/components/Chip/Chip.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/Table/table.tsx
  client/src/shared/components/modals/background/backgrondView.tsx
  client/src/shared/components/modals/background/backgroundView.module.scss
  client/src/shared/components/modals/classModal/classModal.component.tsx
  client/src/shared/components/modals/featModal/featView.module.scss
  client/src/shared/components/modals/featModal/featView.tsx
  client/src/shared/components/modals/raceView/raceView.module.scss
  client/src/shared/components/modals/raceView/raceView.tsx
  client/src/shared/components/modals/spellModal/spellModal.component.tsx
  client/src/shared/components/modals/spellModal/spellModal.module.scss
  client/src/shared/components/paginator/paginator.module.scss
Labels: bug, enhancement, MVP
