Repository ColeHend/serving-solid-characters, pull requests merged in 2025-08, with the labels that each got.

#96 Add Docker support with multi-stage build and Docker Compose configur…
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
  Program.cs
  README.md
  docker-compose.yml
Labels: enhancement, MVP

#97 Enhance CI/CD pipeline with Docker support and deployment script for …
  .github/workflows/build.yml
  README.md
  docker-compose.prod.yml
  scripts/deploy.sh
Labels: enhancement, MVP

#102 prodworks
  Program.cs
  SharpAnglesTemplate.csproj
  client/src/shared/customHooks/utility/tools/httpClientObs.ts
  docker-compose.prod.yml
  tools/DbJsonTool.cs
Labels: enhancement

#103 feat: implement unified local HTTPS setup for .NET API and Vite dev s…
  .gitignore
  192.168.1.100+3-key.pem
  192.168.1.100+3.pem
  Program.cs
  README.md
  client/src/App.tsx
  client/src/components/homebrew/create/homebrewManager.ts
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/models/character.model.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDBackgrounds.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDClasses.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDFeats.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDItems.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDRaces.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDSpells.ts
  client/vite.config.ts
  nethost.pfx
  scripts/gen-dev-cert.sh
Labels: enhancement

#105 Style-update
  client/src/App.module.scss
  client/src/App.tsx
  client/src/components/DataTransfering/Export/Exporting.tsx
  client/src/components/DataTransfering/Import/Importing.tsx
  client/src/components/DataTransfering/Import/importing.module.scss
  client/src/components/DataTransfering/dataTransferModal.tsx
  client/src/components/characters/characters.tsx
  client/src/components/characters/create/create.tsx
  client/src/components/characters/view/stat-bar/stat/stat.tsx
  client/src/components/characters/view/stat-bar/statBar.tsx
  client/src/components/characters/view/view.module.scss
  client/src/components/characters/view/view.tsx
  client/src/components/infoTab/Backgrounds/backgroundMenu/backgroundMenu.tsx
  client/src/components/infoTab/Backgrounds/backgrounds.module.scss
  client/src/components/infoTab/Backgrounds/backgrounds.tsx
  client/src/components/infoTab/Feats/featMenu/featMenu.module.scss
  client/src/components/infoTab/Feats/featMenu/featMenu.tsx
  client/src/components/infoTab/Feats/feats.tsx
  client/src/components/infoTab/Races/races.tsx
  client/src/components/infoTab/Spells/Spells.module.scss
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/components/infoTab/Spells/searchBar/searchBar.module.scss
  client/src/components/infoTab/Spells/searchBar/searchBar.tsx
  client/src/components/infoTab/Spells/spellMenu/spellMenu.module.scss
  client/src/components/infoTab/Spells/spellMenu/spellMenu.tsx
  client/src/components/infoTab/items/item.tsx
  client/src/components/infoTab/items/parts/Weapons/Weapons.tsx
  client/src/components/infoTab/items/parts/Weapons/weaponMenu/weaponMenu.tsx
  client/src/components/infoTab/viewClasses/classMenu/classMenu.tsx
  client/src/components/infoTab/viewClasses/viewClasses.module.scss
  client/src/components/infoTab/viewClasses/viewClasses.tsx
  client/src/components/navbar/navbar.module.scss
  client/src/components/navbar/navbar.tsx
  client/src/components/rootApp.tsx
  client/src/shared/components/modals/background/backgrondView.tsx
  client/src/shared/components/modals/classModal/classModal.component.tsx
  client/src/shared/components/modals/featModal/featView.tsx
  client/src/shared/components/paginator/paginator.tsx
  client/src/shared/customHooks/dndInfo/useCharacters.ts
  client/src/shared/customHooks/dndInfo/useGetFullStats.ts
  client/src/shared/customHooks/homebrewSearch.ts
  client/src/shared/customHooks/utility/style/styleHook.ts
  client/src/shared/customHooks/utility/style/themes/themeStyle.module.scss
Labels: bug, enhancement, MVP

#107 Slade a/style update part2
  client/src/components/infoTab/Races/raceMenu/raceMenu.tsx
  client/src/components/infoTab/Races/races.module.scss
  client/src/components/infoTab/Races/races.tsx
  client/src/components/infoTab/Spells/Spells.module.scss
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/components/infoTab/Spells/spellMenu/spellMenu.tsx
  client/src/components/infoTab/items/parts/Armors/Armors.module.scss
  client/src/components/infoTab/items/parts/Armors/Armors.tsx
  client/src/components/infoTab/items/parts/Armors/armorMenu/armorMenu.tsx
  client/src/components/infoTab/items/parts/Weapons/Weapons.tsx
  client/src/components/infoTab/items/parts/Weapons/weaponMenu/weaponMenu.tsx
  client/src/components/infoTab/items/parts/Weapons/weapons.module.scss
  client/src/models/old/spell.model.ts
  client/src/shared/components/SearchBar/SearchBar.module.scss
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/modals/spellModal/spellModal.component.tsx
  client/src/shared/customHooks/utility/tools/Tools.ts
  models/entities/SpellEntity.cs
Labels: bug, enhancement, MVP

#111 Coleh version selector
  client/src/App.tsx
  client/src/components/characters/view/view.tsx
  client/src/components/homebrew/create/parts/items/items.tsx
  client/src/components/homebrew/create/parts/spells/spells.tsx
  client/src/components/homebrew/create/parts/subclasses/subclasses.tsx
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/components/infoTab/Spells/searchBar/searchBar.tsx
  client/src/components/navMenu/settingsPopup.tsx
  client/src/components/rootApp.tsx
  client/src/models/data/spell.ts
  client/src/models/index.ts
  client/src/models/old/class.model.ts
  client/src/models/old/spell.model.ts
  client/src/models/trade.model.ts
  client/src/models/userSettings.ts
  client/src/shared/components/modals/spellModal/spellModal.component.tsx
  client/src/shared/components/paginator/paginator.tsx
  client/src/shared/customHooks/dndInfo/info/all/spells.ts
  client/src/shared/customHooks/dndInfo/info/srd/spells.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetSpells.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDSpells.ts
  client/src/shared/customHooks/dndInfo/useGetFullStats.ts
  client/src/shared/customHooks/homebrewManager.ts
  client/src/shared/customHooks/index.ts
  client/src/shared/customHooks/userSettings.ts
  client/src/shared/customHooks/utility/localDB/new/srdDB2024.ts
  client/src/shared/customHooks/utility/localDB/old/localDB.ts
  client/src/shared/customHooks/utility/tools/Tools.ts
  data/srd/2024/spells.json
  models/DTO/Class5e.cs
Labels: enhancement

#112 coles library update
  .github/copilot-instructions.md
  client/package-lock.json
  client/package.json
  client/src/components/infoTab/Spells/Spells.tsx
Labels: bug, enhancement

#113 Slade a/updates
  client/eslint.config.js
  client/src/components/infoTab/Backgrounds/backgroundMenu/backgroundMenu.tsx
  client/src/components/infoTab/Backgrounds/backgrounds.module.scss
  client/src/components/infoTab/Backgrounds/backgrounds.tsx
  client/src/components/infoTab/Feats/featMenu/featMenu.tsx
  client/src/components/infoTab/Feats/feats.module.scss
  client/src/components/infoTab/Feats/feats.tsx
  client/src/components/infoTab/Races/raceMenu/raceMenu.tsx
  client/src/components/infoTab/Races/races.tsx
  client/src/components/infoTab/Spells/Spells.tsx
  client/src/components/infoTab/items/item.tsx
  client/src/components/infoTab/viewClasses/viewClasses.module.scss
  client/src/components/infoTab/viewClasses/viewClasses.tsx
  client/src/components/navMenu/navMenu.tsx
  client/src/components/navbar/navMenu/navMenu.tsx
  client/src/components/navbar/navbar.tsx
  client/src/shared/components/modals/background/backgrondView.tsx
  client/src/shared/components/modals/background/backgroundView.module.scss
  client/src/shared/components/modals/classModal/classModal.component.tsx
  client/src/shared/components/modals/classModal/classModal.module.scss
  client/src/shared/components/modals/classModal/featureTable/featureTable.tsx
  client/src/shared/components/modals/damageCalculator/damageCalculator.tsx
  client/src/shared/components/modals/featModal/featView.module.scss
  client/src/shared/components/modals/featModal/featView.tsx
  client/src/shared/components/modals/raceView/raceView.tsx
  client/src/shared/components/modals/spellModal/spellModal.component.tsx
  client/src/shared/customHooks/dndInfo/info/all/backgrounds.ts
  client/src/shared/customHooks/dndInfo/info/all/feats.ts
  client/src/shared/customHooks/dndInfo/info/all/races.ts
  client/src/shared/customHooks/dndInfo/info/srd/backgrounds.ts
  client/src/shared/customHooks/dndInfo/info/srd/feats.ts
  client/src/shared/customHooks/dndInfo/info/srd/races.ts
  data/srd/2024/races.json
Labels: bug, enhancement, MVP

#118 Cole homebrew update
  .github/copilot-instructions.md
  Repositories/SrdInfoRepository.cs
  client/package-lock.json
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/homebrew/create/parts/classes/__tests__/classes.component.test.tsx
  client/src/components/homebrew/create/parts/classes/classAdapter.ts
  client/src/components/homebrew/create/parts/classes/classTable.tsx
  client/src/components/homebrew/create/parts/classes/classes.tsx
  client/src/components/homebrew/create/parts/classes/featureModal.tsx
  client/src/components/homebrew/create/parts/classes/featureTable.tsx
  client/src/components/homebrew/create/parts/classes/header.tsx
  client/src/components/homebrew/create/parts/classes/itemMenuButton.tsx
  client/src/components/homebrew/create/parts/classes/items.tsx
  client/src/components/homebrew/create/parts/classes/proficiencies.tsx
  client/src/shared/customHooks/__tests__/homebrewManager.test.ts
  client/src/shared/customHooks/dndInfo/info/all/classesFiltered.ts
  client/src/shared/customHooks/dndInfo/info/all/items.ts
  client/src/shared/customHooks/dndInfo/info/all/magicItems.ts
  client/src/shared/customHooks/dndInfo/info/all/masteries.ts
  client/src/shared/customHooks/dndInfo/info/all/subclasses.ts
  client/src/shared/customHooks/dndInfo/info/all/subraces.ts
  client/src/shared/customHooks/dndInfo/info/homebrew/classes.ts
  client/src/shared/customHooks/dndInfo/info/srd/backgrounds.ts
  client/src/shared/customHooks/dndInfo/info/srd/items.ts
  client/src/shared/customHooks/dndInfo/info/srd/magicItems.ts
  client/src/shared/customHooks/dndInfo/info/srd/masteries.ts
  client/src/shared/customHooks/dndInfo/info/srd/races.ts
  client/src/shared/customHooks/dndInfo/info/srd/subclasses.ts
  client/src/shared/customHooks/dndInfo/info/srd/subraces.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetClasses.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDItems.ts
  client/src/shared/customHooks/homebrewManager.ts
  client/src/shared/customHooks/homebrewManager5e.ts
  client/src/shared/customHooks/utility/localDB/old/localDB.ts
  client/src/test/mocks/coles-solid-library/dist/components/Form/formHelp/models.ts
  client/src/test/mocks/coles-solid-library/index.ts
  client/src/test/mocks/coles-solid-library/index.tsx
  client/src/test/mocks/coles-solid-library/themes/themes.scss
  client/src/test/mocks/coles-solid-library/themes/variables.scss
  client/src/useTest.ts
  client/vitest.config.ts
  data/srd/2024/classes.json
  data/srd/2024/items.json
  models/DTO/Class5e.cs
  models/enums.cs
Labels: bug

#119 feat: update coles-solid-library to version 0.3.8 and refactor class …
  Repositories/SrdInfoRepository.cs
  client/package-lock.json
  client/package.json
  client/src/components/homebrew/create/parts/classes/__tests__/classes.component.test.tsx
  client/src/components/homebrew/create/parts/classes/classAdapter.ts
  client/src/components/homebrew/create/parts/classes/classes.tsx
  client/src/components/homebrew/create/parts/classes/featureModal.tsx
  client/src/components/homebrew/create/parts/classes/items.tsx
  client/src/components/homebrew/create/parts/classes/stats.tsx
  client/src/components/homebrew/view/table/Table.tsx
  client/src/components/homebrew/view/view.tsx
  client/src/components/infoTab/viewClasses/classMenu/classMenu.tsx
  client/src/components/navMenu/navMenu.tsx
  client/src/models/data/classes.ts
  client/src/shared/components/modals/classModal/featureTable/featureTable.tsx
  models/DTO/Class5e.cs
Labels: bug, enhancement
