Repository ColeHend/serving-solid-characters, pull requests merged in 2025-09, with the labels that each got.

#122 Slade a/items finsh
  client/src/App.tsx
  client/src/components/aboutPage/about.tsx
  client/src/components/characters/view/view.tsx
  client/src/components/homebrew/create/parts/backgrounds/backgrounds.tsx
  client/src/components/homebrew/create/parts/feats/feats.tsx
  client/src/components/homebrew/create/parts/items/items.tsx
  client/src/components/homebrew/create/parts/races/races.tsx
  client/src/components/homebrew/create/parts/spells/spells.tsx
  client/src/components/homebrew/create/parts/subclasses/SpellcastingSection.tsx
  client/src/components/homebrew/create/parts/subclasses/subclasses.tsx
  client/src/components/homebrew/create/parts/subraces/subraces.tsx
  client/src/components/infoTab/Backgrounds/backgrounds.tsx
  client/src/components/infoTab/items/item.tsx
  client/src/components/infoTab/items/parts/items/itemsView.module.scss
  client/src/components/infoTab/items/parts/items/itemsView.tsx
  client/src/components/infoTab/items/parts/weapon/weaponView.tsx
  client/src/components/infoTab/items/parts/weapon/weaponsView.module.scss
  client/src/components/navbar/navbar.module.scss
  client/src/components/rootApp.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/modals/ItemModal/ItemModal.tsx
  client/src/shared/components/modals/ItemModal/itemsModal.module.scss
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetBackgrounds.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetClasses.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetFeats.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetItems.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/data/useGetRaces.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/fixClasses.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDBackgrounds.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDClasses.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDFeats.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDItems.ts
  client/src/shared/customHooks/dndInfo/oldSrdinfo/useDnDRaces.ts
  client/src/shared/customHooks/dndInfo/useGetFullStats.ts
  client/src/shared/customHooks/homebrewSearch.ts
  client/src/shared/customHooks/index.ts
Labels: bug, enhancement, MVP

#123 Coleh homebrew updates
  client/src/App.tsx
  client/src/components/homebrew/create/parts/backgrounds/sections/__tests__/equipmentSection.interaction.test.tsx
  client/src/components/homebrew/create/parts/races/__tests__/abilityBonusesSection.render.test.tsx
  client/src/components/homebrew/create/parts/races/__tests__/mapping.test.ts
  client/src/components/homebrew/create/parts/races/__tests__/store.actions.test.ts
  client/src/components/homebrew/create/parts/races/__tests__/validation.test.ts
  client/src/components/homebrew/create/parts/races/races.module.scss
  client/src/components/homebrew/create/parts/races/races.tsx
  client/src/components/homebrew/create/parts/races/racesStore.ts
  client/src/components/homebrew/create/parts/races/sections/AbilityBonusesSection.tsx
  client/src/components/homebrew/create/parts/races/sections/IdentitySection.tsx
  client/src/components/homebrew/create/parts/races/sections/LanguagesSection.tsx
  client/src/components/homebrew/create/parts/races/sections/SaveBar.tsx
  client/src/components/homebrew/create/parts/races/sections/TraitsSection.tsx
  client/src/components/homebrew/create/parts/races/sections/__tests__/traitsSection.interaction.test.tsx
  client/src/components/homebrew/create/parts/races/validation.ts
  client/src/components/homebrew/create/parts/subclasses/CoreFields.tsx
  client/src/components/homebrew/create/parts/subclasses/FeaturesSection.tsx
  client/src/components/homebrew/create/parts/subclasses/__tests__/subclasses.behavior.test.tsx
  client/src/components/homebrew/create/parts/subclasses/subclassAdapter.ts
  client/src/components/homebrew/create/parts/subclasses/subclasses.tsx
  client/src/components/homebrew/create/parts/subraces/AbilitySection.tsx
  client/src/components/homebrew/create/parts/subraces/IdentitySection.tsx
  client/src/components/homebrew/create/parts/subraces/LanguageSection.tsx
  client/src/components/homebrew/create/parts/subraces/SaveSection.tsx
  client/src/components/homebrew/create/parts/subraces/TraitsSection.tsx
  client/src/components/homebrew/create/parts/subraces/__tests__/helpers.test.ts
  client/src/components/homebrew/create/parts/subraces/__tests__/subraces.component.test.tsx
  client/src/components/homebrew/create/parts/subraces/helpers.ts
  client/src/components/homebrew/create/parts/subraces/subraces.module.scss
  client/src/components/homebrew/create/parts/subraces/subraces.tsx
  client/src/components/homebrew/create/parts/subraces/useSubraceEditor.ts
  client/src/components/homebrew/view/view.tsx
  client/src/shared/components/modals/raceView/raceView.tsx
  client/src/shared/constants/homebrew.ts
  client/src/shared/customHooks/homebrewManager.ts
  client/src/shared/index.ts
  client/src/test/mocks/coles-solid-library/index.tsx
Labels: bug, enhancement

#124 Cole homebrew alpha
  client/src/components/homebrew/create/parts/feats/feats.test.tsx
  client/src/components/homebrew/create/parts/feats/feats.tsx
  client/src/components/homebrew/create/parts/items/ArmorSection.tsx
  client/src/components/homebrew/create/parts/items/FeaturesSection.tsx
  client/src/components/homebrew/create/parts/items/IdentitySection.tsx
  client/src/components/homebrew/create/parts/items/SaveSection.tsx
  client/src/components/homebrew/create/parts/items/Section.tsx
  client/src/components/homebrew/create/parts/items/TagsSection.tsx
  client/src/components/homebrew/create/parts/items/WeaponSection.tsx
  client/src/components/homebrew/create/parts/items/__tests__/items.featureModal.test.tsx
  client/src/components/homebrew/create/parts/items/__tests__/itemsStore.behavior.test.ts
  client/src/components/homebrew/create/parts/items/__tests__/itemsStore.edgecases.test.ts
  client/src/components/homebrew/create/parts/items/items.module.scss
  client/src/components/homebrew/create/parts/items/items.tsx
  client/src/components/homebrew/create/parts/items/itemsStore.ts
  client/src/components/infoTab/Feats/feats.tsx
  client/src/shared/customHooks/__tests__/homebrewManager.test.ts
  client/src/shared/customHooks/dndInfo/info/srd/feats.ts
  client/src/shared/customHooks/homebrewManager.ts
  client/src/test/mocks/coles-solid-library/index.ts
Labels: enhancement

#125 chore: update dependencies to latest versions and improve homebrewMan…
  client/package-lock.json
  client/package.json
  client/src/shared/customHooks/homebrewManager.ts
Labels: bug
